spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:./users
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate

user-cache:
  maxSize: 1000000
  expireInMinutes: 60


management:
  info:
    os:
      enabled: true
    java:
      enabled: true
  metrics:
    enable:
      tomcat: true
      jvm: true
      process: true
      hikaricp: true
      system: true
      jdbc: true
      logback: true
#    distribution:
#      percentiles:
#        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
#      slo:
#        http.server.requests: 1ms, 10ms, 50ms
#      percentiles-histogram:
#        http.server.requests: true
#  endpoint:
#    loggers:
#      enabled: true
#    metrics:
#      enabled: true
#  export:
#    prometheus:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'